// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4h2rO1V4nzEdmRFjzUVZNlnqMI7BtK5o',
    appId: '1:276505697675:android:64bea5158c933f9982238e',
    messagingSenderId: '276505697675',
    projectId: 'chatbox-57508',
    storageBucket: 'chatbox-57508.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbmisOw6DRFMh450DtZDAhTZ-aiyOlYnw',
    appId: '1:276505697675:ios:d3b5a85a4eba5ce982238e',
    messagingSenderId: '276505697675',
    projectId: 'chatbox-57508',
    storageBucket: 'chatbox-57508.appspot.com',
    iosBundleId: 'com.example.zoomClone',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFHWAhPIaiT-KhZ9BCIQgtzKej5Y8Oxpc',
    appId: '1:276505697675:web:e98ab0eaf8de3fa982238e',
    messagingSenderId: '276505697675',
    projectId: 'chatbox-57508',
    authDomain: 'chatbox-57508.firebaseapp.com',
    storageBucket: 'chatbox-57508.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbmisOw6DRFMh450DtZDAhTZ-aiyOlYnw',
    appId: '1:276505697675:ios:d3b5a85a4eba5ce982238e',
    messagingSenderId: '276505697675',
    projectId: 'chatbox-57508',
    storageBucket: 'chatbox-57508.appspot.com',
    iosBundleId: 'com.example.zoomClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFHWAhPIaiT-KhZ9BCIQgtzKej5Y8Oxpc',
    appId: '1:276505697675:web:ad40b7aba34dc06282238e',
    messagingSenderId: '276505697675',
    projectId: 'chatbox-57508',
    authDomain: 'chatbox-57508.firebaseapp.com',
    storageBucket: 'chatbox-57508.appspot.com',
  );

}